[tool.poetry]
name = "pystematic"
version = "0.3.0"
description = "A framework that helps you setup and run reproducible experiments."
repository = ""
documentation = ""
license = "MIT"
readme = "README.rst"
authors = ["E.Valldor"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Topic :: Scientific/Engineering"
]

[tool.poetry.dependencies]
python = "^3.8"
tqdm = "^4.48.2"
tensorboardX = "^2.1"
numpy = "^1.19.1"
torch = "^1.8.1"
torchvision = "^0.9.1"
PyYAML = "^5.3.1"
wrapt = "^1.12.1"
matplotlib = "^3.3.4"
rich = "^10.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.6.0"
Sphinx = "^3.5.2"
sphinx-rtd-theme = "^0.5.2"
autopep8 = "^1.5.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
